### ISSUE TITLE
server won't run

### ISSUE THREAD

**Issue by denlabs** [andrew-hamilton-dev/angular-1.5-typescript-seed#2]
I cloned the repo and followed the install outlined in the readme but the app fails to start.  I'm seeing this repeatedly in the startup logs: 
dev/typings/browser/ambient/angular-component-router/index.d.ts
(49,29): error TS2304: Cannot find name 'Promise'.

any ideas?

**Comment by andrew-hamilton-dev** [comment]
I have updated the version of typings used for this seed.  It should help resolve any typing issues like this.  The version of angular-component-router typings it was using had some issues apparently.
